# Render up to...
upto: "20130111"

# Site Configuration
title: Better Apps for a Better World
tagline: Apps are made by people like you.

short: BA4ABW
number: CSC 186

markdown: kramdown
# This is the date that we render "upto."

# Colors
borders: "#911"
highlight: "#C33"
links: "#B22"
strong: "#735"
  
# Paths
## There are no heirarchies of variables; therefore, every
## path must be complete. A search-replace is necessary with
## any change to base.
base: /courses/ba4abw-sp13
media: /courses/ba4abw-sp13/media
arse:
    expanded: 'Active Reading Support Environment'
    url: '/courses/ba4abw-sp13/media/active-reading-support-environment.docx'
    version: '1.0'

moodle:
    a1: http://moodle.berea.edu/blahblahblah/vid?1234

# http://db.tt/zgUQOl6A
# Shortcuts
pdf: <img src="/courses/ba4abw-sp13/images/mini-pdf.png" />
word: <img src="/courses/ba4abw-sp13/images/mini-word.png" />
pdf: '<img src="/courses/ba4abw-sp13/images/mini-pdf.png" />'
word: '<img src="/courses/ba4abw-sp13/images/mini-word.png" />'
group: '<i class="icon-group" style="margin-top: 6px;"></i>'
lab: '<i class="icon-beaker" style="margin-top: 6px;"></i>'
reading: '<i class="icon-book" style="margin-top: 6px;"></i>'
prof: '<i class="icon-bullhorn" style="margin-top: 6px;"></i>'
video: '<i class="icon-camera" style="margin-top: 6px;"></i>'
download: '<i class="icon-download-alt" style="margin-top: 6px;"></i>'
cloud: '<i class="icon-cloud" style="margin-top: 6px;"></i>'
cart: '<i class="icon-shopping-cart" style="margin-top: 6px;"></i>'

# Server Config
permalink: /:categories/:title

# My Config
# This needs to be expanded for team-taught courses.
prof-names: ['Matt Jadud', 'Jan Pearce']
prof-firsts: ['Matt', 'Jan']
prof-urls: ['http://www.berea.edu/csc/matt-jadud/', 'http://faculty.berea.edu/pearcej/']
prof-phones: ['925-238-3692', '859-985-3569']
prof-offices: ['Danforth 102B', 'Danforth 102C']
prof-office-hours: ['M 9:30-11:30 and T 13:30-15:30', 'TR 10:00-10:50 and MWF: 9:30-10:20']
prof-emails: ['jadudm@berea', 'pearcej@berea']
berea-cs-url: http://cs.berea.edu/
